<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <OutputType>WinExe</OutputType> 	  
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <Nullable>enable</Nullable>
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	  <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <Authors>David Wang</Authors>
    <Company>David Wang</Company>
    <Copyright>Copyright © 2026 David Wang</Copyright>
    <Title>工资计算器</Title>
    <Version>7.2.1.0</Version>
    <AssemblyVersion>7.2.1.0</AssemblyVersion>
    <FileVersion>7.2.1.0</FileVersion>
    <InformationalVersion>7.2.1.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <StartupObject>SalaryCalculatorApp.App</StartupObject>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <SignAssembly>False</SignAssembly>
    <Product>工资计算器</Product>
    <AssemblyName>工资计算器v$(FileVersion)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="SalaryCalculatorApp.Tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="SalaryCalculatorApp.Tests\**\*.cs" />
    <EmbeddedResource Remove="SalaryCalculatorApp.Tests\**\*" />
    <None Remove="SalaryCalculatorApp.Tests\**\*" />
    <Page Remove="SalaryCalculatorApp.Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.0.8" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

</Project>
